# Generated by Django 3.2.8 on 2021-11-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_Add_field_user_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sum_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
