# Generated by Django 3.2.8 on 2021-12-29 21:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_convert_name_latin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_confirm', 'waiting_confirm'), ('confirmed', 'confirmed'), ('shipping', 'shipping'), ('success', 'success'), ('cancel', 'cancel')], default='waiting_confirm', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
