# Generated by Django 3.2.8 on 2022-01-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_images_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
