# Generated by Django 3.2.8 on 2022-01-06 10:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_images_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
